# Generated by Django 2.2 on 2019-04-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=30)),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='валюта')),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('is_debt_account', models.BooleanField()),
                ('take_into_balance', models.BooleanField()),
            ],
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('monthly_plan', models.IntegerField(blank=True, null=True)),
            ],
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('plan', models.IntegerField(blank=True, null=True)),
            ],
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('monthly_plan', models.IntegerField(blank=True, null=True)),
            ],
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('data_from', models.DateField()),
                ('data_to', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(max_length=100)),
                ('transaction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='froms', to='main.FinancialNode')),
                ('transaction_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos', to='main.FinancialNode')),
            ],
        ),
    ]
