# Generated by Django 2.2 on 2019-05-11 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=30)),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='валюта')),
                ('delete', models.BooleanField(default=False)),
                ('create_on', models.DateField(default=datetime.date(2019, 5, 11))),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='financial_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('is_debt_account', models.BooleanField()),
                ('take_into_balance', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('monthly_plan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('plan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('financialnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.FinancialNode')),
                ('monthly_plan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('main.financialnode',),
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='BYN', max_length=3)),
                ('bank_login', models.CharField(max_length=50, null=True)),
                ('bank_password', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additonal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('data_from', models.DateField()),
                ('data_to', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(default='', max_length=100)),
                ('delete', models.BooleanField(default=False)),
                ('choice_currency', models.CharField(default='BYN', max_length=3)),
                ('transaction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.FinancialNode')),
                ('transaction_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='main.FinancialNode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_from'],
            },
        ),
    ]
