# Generated by Django 2.2 on 2019-05-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_debt_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='take_into_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='monthly_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='monthly_plan',
            field=models.IntegerField(default=0),
        ),
    ]
