# Generated by Django 2.2 on 2019-04-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.FinancialNode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='main.FinancialNode'),
        ),
    ]
