# Generated by Django 2.2 on 2019-04-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_useradditionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialnode',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='financial_nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
