# Generated by Django 2.2 on 2019-04-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_financialnode_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialnode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
