# Generated by Django 2.2 on 2019-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transaction_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-data_from']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='choice_currency',
            field=models.CharField(default='BYN', max_length=3),
        ),
    ]
