# Generated by Django 2.2 on 2019-04-30 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_financialnode_create_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialnode',
            name='create_on',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 10, 48, 44, 747788, tzinfo=utc)),
        ),
    ]
